# Generated by Django 5.0 on 2023-12-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot_integration', '0003_alter_hubspotuser_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubspotuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
