# Generated by Django 5.0 on 2023-12-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot_integration', '0005_hubspotuser_hs_object_id_alter_hubspotuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubspotuser',
            name='hs_object_id',
        ),
        migrations.AlterField(
            model_name='hubspotuser',
            name='firstname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hubspotuser',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
    ]
