# Generated by Django 5.0 on 2023-12-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot_integration', '0008_remove_hubspotuser_hubspot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubspotuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
