# Generated by Django 5.0 on 2023-12-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubspotuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='hubspotuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='hubspotuser',
            name='firstname',
            field=models.CharField(default='ValorPredeterminado', max_length=255),
        ),
        migrations.AddField(
            model_name='hubspotuser',
            name='lastname',
            field=models.CharField(default='ValorPredeterminado', max_length=255),
        ),
        migrations.AlterField(
            model_name='hubspotuser',
            name='email',
            field=models.EmailField(default='ValorPredeterminado', max_length=254, unique=True),
        ),
    ]
