# Generated by Django 5.0 on 2023-12-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot_integration', '0004_alter_hubspotuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspotuser',
            name='hs_object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hubspotuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='hubspotuser',
            name='firstname',
            field=models.CharField(default='ValorPredeterminado', max_length=255),
        ),
        migrations.AlterField(
            model_name='hubspotuser',
            name='lastname',
            field=models.CharField(default='ValorPredeterminado', max_length=255),
        ),
    ]
