# Generated by Django 5.0 on 2023-12-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot_integration', '0006_remove_hubspotuser_hs_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubspotuser',
            name='hubspot_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
