# Generated by Django 5.0 on 2023-12-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot_integration', '0007_hubspotuser_hubspot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubspotuser',
            name='hubspot_id',
        ),
    ]
